require("personal.set")
require("personal.auto-session")
require("personal.remap")
require("personal.ui")
require("personal.mini")
require("personal.surround")
require("personal.which-key")
require("personal.trouble")
require("personal.nui")
require("personal.snacks")
require("personal.fff")
require("personal.treesitter")
require("personal.markdown")
require("personal.harpoon")
require("personal.luasnip")
require("personal.lsp")
require("personal.lint")
require("personal.format")
require("personal.git")
require("personal.fidget")
require("personal.flash")
require("personal.yanky")

require("personal.actions").setup()
require("personal.utils.config").pack_sync()

vim.cmd("packadd nvim.undotree")
