require("kolahan.set")
require("kolahan.remap")
require("kolahan.icons")
require("kolahan.which-key")
require("kolahan.snacks")
require("kolahan.colorscheme")
require("kolahan.treesitter")
require("kolahan.harpoon")
require("kolahan.lsp")
require("kolahan.mason")
require("kolahan.auto-session")
require("kolahan.bufferline")
require("kolahan.git")
vim.cmd("packadd nvim.undotree")
